feat: add app icon
nobelization/panoramax-mobile-app pull request #30
Opened 2024-04-19 14:03 UTC by OtterWays

2024-04-19 22:31 UTC, Jean-BaptisteC commented
App icon is not available in SVG?

2024-04-20 07:17 UTC, luifr10 requested changes
I have the feeling that above a certain size the logo looks pixelated, the rendering could be better if a svg was used as suggested by @Jean-BaptisteC  (if available of course).

2024-04-20 07:17 UTC, luifr10 commented on pubspec.yaml
> +  flutter_launcher_icons: ^0.13.1
This package seems useful to me when the logos are different between platforms.
If we use the same icons for all platforms, I think we can do without it, and for Android, I also suggest that you replace the "ic_launcher.png" files with the logo, so the settings do not have to be changed.

2024-04-20 10:25 UTC, Jean-BaptisteC commented
Use SVG on Android add ability to have only one drawable for all dpi size screen. And add ability to support [theming app icon](https://developer.android.com/develop/ui/views/launch/icon_design_adaptive?hl=fr)

2024-04-20 11:33 UTC, OtterWays commented
Android and iOS do not support SVG images for launch icons. However, the logo image may not be large enough to work in high resolution

2024-04-20 16:41 UTC, Jean-BaptisteC commented
Not support of SVG for launchs icons on Android is a limitation of flutter?

2024-04-20 17:47 UTC, OtterWays commented
No, it's an Android limitation. It's possible (and encouraged) to use an SVG image for all icons and images but not for launch icon

2024-04-22 21:19 UTC, Jean-BaptisteC commented
The launcher icon is good but we have to use a drawable SVG for the splashscreen, png is very ugly.

2024-04-23 07:12 UTC, OtterWays commented
> The launcher icon is good but we have to use a drawable SVG for the splashscreen, png is very ugly.

Yes of course. All other images will be SVG, including the splashscreen

2024-04-23 07:14 UTC, merged